# Generated by Django 3.1.2 on 2020-10-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_clientdetials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientDetials',
            new_name='ClientDetails',
        ),
    ]
