# Generated by Django 3.1.2 on 2020-11-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_itemstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStorageMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.items')),
                ('item_storage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itemstorage')),
            ],
        ),
    ]
