# Generated by Django 3.1 on 2021-06-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
