# Generated by Django 3.1 on 2021-06-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
