# Generated by Django 3.1 on 2021-06-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210605_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variations_category',
            new_name='variation_category',
        ),
    ]
