# Generated by Django 3.1.2 on 2020-10-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_supplieraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieraddress',
            name='hello',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
