# Generated by Django 3.1.2 on 2020-10-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201021_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieraddress',
            name='hello',
        ),
    ]
