# Generated by Django 3.1.2 on 2020-10-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_supplieraddress_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieraddress',
            name='hello',
            field=models.CharField(blank=True, default='Hello World', max_length=100, null=True),
        ),
    ]
