# Generated by Django 3.1.2 on 2020-10-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.FileField(upload_to='clients/%Y/%m/%d/'),
        ),
    ]
