# Generated by Django 3.1.2 on 2020-10-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201026_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(upload_to='clients/%Y/%m/%D/'),
        ),
    ]
