# Generated by Django 3.1.2 on 2020-10-27 09:31

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201027_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('addresstype', django_enumfield.db.fields.EnumField(default=1, enum=api.models.AddressTypeEnum)),
                ('branch_as', models.CharField(blank=True, max_length=100, null=True)),
                ('care_of_person', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('office_number', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('fax_number', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'verbose_name_plural': 'ClientAddress',
            },
        ),
    ]
