# Generated by Django 3.1.2 on 2020-10-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_currency_paymentterms_supplierdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='country',
            new_name='country_id',
        ),
    ]
