# Generated by Django 3.1.2 on 2020-10-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201027_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_acc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_balance', models.FloatField(default=0)),
                ('open_bal_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pay_recurring', models.BooleanField(default=False)),
                ('late_fees', models.BooleanField(default=False)),
                ('pay_reminder', models.BooleanField(default=False)),
                ('tax_exemption', models.BooleanField(default=False)),
                ('send_invitation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
                ('currency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
                ('pay_term_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentterms')),
            ],
        ),
    ]
