# Generated by Django 3.1.2 on 2020-10-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201028_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('acc_code', models.IntegerField()),
                ('acc_start_date', models.DateTimeField(auto_now_add=True)),
                ('opening_balance', models.FloatField(default=0)),
                ('is_editable', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('acc_type_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('SKU', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_price', models.FloatField(blank=True, default=0, null=True)),
                ('sales_price', models.FloatField(default=0)),
                ('markup_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_sales_price', models.FloatField(blank=True, default=0, null=True)),
                ('weight_param', models.CharField(max_length=100)),
                ('weight_values', models.FloatField(default=0)),
                ('volume_cbm', models.FloatField(default=0)),
                ('upc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mpn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ean_no', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('item_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_month', models.IntegerField(blank=True, null=True)),
                ('stock_in_hand', models.FloatField(default=0)),
                ('initial_stock_entry', models.DateTimeField(auto_now_add=True)),
                ('reorder_point', models.IntegerField(blank=True, null=True)),
                ('max_stock_no', models.IntegerField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('allow_sales_commision', models.BooleanField(default=True)),
                ('commission_per_item', models.IntegerField()),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tags', models.CharField(max_length=100)),
                ('account_name_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accountname')),
                ('item_brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itembrands')),
                ('item_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itemcategory')),
                ('item_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itemtype')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='accountname',
            name='account_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounttype'),
        ),
    ]
