# Generated by Django 3.1.2 on 2020-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_itemgroupmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head_of_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('head_acc_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=False)),
            ],
        ),
    ]
