# Generated by Django 3.1.2 on 2020-11-02 10:53

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_itemstoragemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('time_log', models.DateTimeField(auto_now_add=True)),
                ('reference_no', models.CharField(max_length=100)),
                ('shipping_method', django_enumfield.db.fields.EnumField(default=1, enum=api.models.ShippingMethodsEnum)),
                ('shipment_tracking_no', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_cost', models.FloatField(default=0)),
                ('bilable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_storage_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_storage', to='api.storagelocation')),
                ('shopping_carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
                ('to_storage_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_storage', to='api.storagelocation')),
            ],
        ),
    ]
