# Generated by Django 3.1.2 on 2020-11-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20201105_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransfer',
            name='time_log',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
