# Generated by Django 3.1.2 on 2020-11-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20201105_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountname',
            name='acc_start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='open_bal_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='initial_stock_entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='open_bal_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
