# Generated by Django 3.1 on 2021-06-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
