# Generated by Django 3.0.4 on 2020-03-07 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200307_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='task_created',
        ),
        migrations.AddField(
            model_name='task',
            name='task_completed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
