# Generated by Django 3.1.2 on 2020-10-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_clientaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('symbol_native', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100)),
                ('no_days', models.IntegerField(blank=True, null=True)),
                ('day_of_mon', models.IntegerField(blank=True, null=True)),
                ('day_next_mon', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('bank_acc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_balance', models.FloatField(default=0)),
                ('open_bal_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pay_recurring', models.BooleanField(default=False)),
                ('is_contractor', models.BooleanField(default=False)),
                ('send_invitation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('currency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
                ('pay_term_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentterms')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
    ]
