# Generated by Django 3.0.3 on 2020-02-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profilefeetitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeetItem',
            new_name='ProfileFeedItem',
        ),
    ]
