# Generated by Django 3.1.2 on 2020-11-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20201103_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Head_of_Accounts',
            new_name='HeadOfAccounts',
        ),
        migrations.RenameModel(
            old_name='Supplier_Additional_Contacts',
            new_name='SupplierAdditionalContacts',
        ),
        migrations.AlterModelOptions(
            name='accountname',
            options={'verbose_name_plural': 'Account Name'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'verbose_name_plural': 'Account Type'},
        ),
        migrations.AlterModelOptions(
            name='clientadditionalcontacts',
            options={'verbose_name_plural': 'Client Additional Contacts'},
        ),
        migrations.AlterModelOptions(
            name='clientaddress',
            options={'verbose_name_plural': 'Client Address'},
        ),
        migrations.AlterModelOptions(
            name='clientdetails',
            options={'verbose_name_plural': 'Client Details'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency'},
        ),
        migrations.AlterModelOptions(
            name='headofaccounts',
            options={'verbose_name_plural': 'Head of Accounts'},
        ),
        migrations.AlterModelOptions(
            name='inventoryadjustment',
            options={'verbose_name_plural': 'Inventory Adjustment'},
        ),
        migrations.AlterModelOptions(
            name='inventoryadjustmentitems',
            options={'verbose_name_plural': 'Inventory Adjustment Items'},
        ),
        migrations.AlterModelOptions(
            name='itembrands',
            options={'verbose_name_plural': 'Item Brands'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AlterModelOptions(
            name='itemgroupmapping',
            options={'verbose_name_plural': 'Item Group Mapping'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemsgroup',
            options={'verbose_name_plural': 'Items Group'},
        ),
        migrations.AlterModelOptions(
            name='itemstorage',
            options={'verbose_name_plural': 'Item Storage'},
        ),
        migrations.AlterModelOptions(
            name='itemstoragemapping',
            options={'verbose_name_plural': 'Item Storage mapping'},
        ),
        migrations.AlterModelOptions(
            name='itemtransfer',
            options={'verbose_name_plural': 'Item Transfer'},
        ),
        migrations.AlterModelOptions(
            name='itemtransfermapping',
            options={'verbose_name_plural': 'Item Tansfer Mapping'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name_plural': 'Item Types'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='paymentterms',
            options={'verbose_name_plural': 'Payment Terms'},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'verbose_name_plural': 'Storage Location'},
        ),
        migrations.AlterModelOptions(
            name='supplieraddress',
            options={'verbose_name_plural': 'Supplier Address'},
        ),
        migrations.AlterModelOptions(
            name='supplierdetails',
            options={'verbose_name_plural': 'Supplier Details'},
        ),
    ]
