# Generated by Django 3.0.2 on 2020-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_email',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
