# Generated by Django 3.1.2 on 2020-11-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20201105_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='photo',
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='acc_type_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientadditionalcontacts',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientadditionalcontacts',
            name='email_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientadditionalcontacts',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientadditionalcontacts',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientadditionalcontacts',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientadditionalcontacts',
            name='mobile_phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientadditionalcontacts',
            name='salutation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientadditionalcontacts',
            name='work_phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='branch_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='care_of_person',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='fax_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='mobile_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='office_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='bank_acc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='open_bal_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clients',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='salutation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headofaccounts',
            name='head_acc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='adjustment_reference_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='cause_of_action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='ean_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='isbn_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='mpn_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='tags',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='upc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='weight_param',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemsgroup',
            name='item_barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemsgroup',
            name='tags',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemsgroup',
            name='upc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='lot_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemstoragemapping',
            name='volume',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='reference_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='shipment_tracking_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemtransfermapping',
            name='volume',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='term_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='corporation_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='salutation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieradditionalcontacts',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieradditionalcontacts',
            name='email_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieradditionalcontacts',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplieradditionalcontacts',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplieradditionalcontacts',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieradditionalcontacts',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieradditionalcontacts',
            name='salutation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieradditionalcontacts',
            name='work_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='branch_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='care_of_person',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='fax_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='mobile_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='office_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='zipcode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='bank_acc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='open_bal_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
